---
- name: RHV Power On/Off a VM
  hosts: "{{ target_host_name }}*"
  gather_facts: no

  tasks:
  - name: Change VM state
    ovirt_vm:
      state: "{{ rhv_vm_state }}"
      name: "{{ name }}"
      cluster: "{{ rhv_cluster_name }}"
    delegate_to: localhost
...