---
- name: RHV delete a VM
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
  - name: Delete VM
    ovirt_vm:
      state: absent
      name: "{{ target_host_name }}"
      cluster: "{{ rhv_cluster_name }}"
...